import { BlockRegistry } from '@school-cms/cms';
import { HeroBannerBlockDefinition } from './hero_banner';
import { ProgramListBlockDefinition } from './program_list';
import { PartnerSliderBlockDefinition } from './partner_slider';
import { BranchListBlockDefinition } from './branch_list';
import { NewsListBlockDefinition } from './news_list';
import { FormEmbedBlockDefinition } from './form_embed';
import { TestimonialSliderBlockDefinition } from './testimonial_slider';
import { FaqAccordionBlockDefinition } from './faq_accordion';
import { StatisticsBlockDefinition } from './statistics';
import { CtaBannerBlockDefinition } from './cta_banner';
import { GalleryBlockDefinition } from './gallery';
import { ContactBoxBlockDefinition } from './contact_box';
import { VideoPlayerBlockDefinition } from './video_player';
import { GoogleMapBlockDefinition } from './google_map';
import { RichTextBlockDefinition } from './rich_text';
import { ImageTextBlockDefinition } from './image_text';

// Tự động đăng ký toàn bộ 16 Block chuẩn vào BlockRegistry theo Open/Closed Principle
BlockRegistry.register(HeroBannerBlockDefinition);
BlockRegistry.register(ProgramListBlockDefinition);
BlockRegistry.register(PartnerSliderBlockDefinition);
BlockRegistry.register(BranchListBlockDefinition);
BlockRegistry.register(NewsListBlockDefinition);
BlockRegistry.register(FormEmbedBlockDefinition);
BlockRegistry.register(TestimonialSliderBlockDefinition);
BlockRegistry.register(FaqAccordionBlockDefinition);
BlockRegistry.register(StatisticsBlockDefinition);
BlockRegistry.register(CtaBannerBlockDefinition);
BlockRegistry.register(GalleryBlockDefinition);
BlockRegistry.register(ContactBoxBlockDefinition);
BlockRegistry.register(VideoPlayerBlockDefinition);
BlockRegistry.register(GoogleMapBlockDefinition);
BlockRegistry.register(RichTextBlockDefinition);
BlockRegistry.register(ImageTextBlockDefinition);

export * from './hero_banner';
export * from './program_list';
export * from './partner_slider';
export * from './branch_list';
export * from './news_list';
export * from './form_embed';
export * from './testimonial_slider';
export * from './faq_accordion';
export * from './statistics';
export * from './cta_banner';
export * from './gallery';
export * from './contact_box';
export * from './video_player';
export * from './google_map';
export * from './rich_text';
export * from './image_text';
